#include "qrcodeboygo.h"
/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void Go2cppFn_QrcodePngToText(char* in, int inLen, char** out, int* outLen);
extern __declspec(dllexport) void Go2cppFn_TextToQrcodePng(char* in, int inLen, char** out, int* outLen);

#ifdef __cplusplus
}
#endif


QrcodePngToText_Resp QrcodePngToText(std::string in0){
	std::string in;
	{
		uint32_t tmp6 = in0.length();
		char tmp7[4];
		tmp7[0] = (uint32_t(tmp6) >> 24) & 0xFF;
		tmp7[1] = (uint32_t(tmp6) >> 16) & 0xFF;
		tmp7[2] = (uint32_t(tmp6) >> 8) & 0xFF;
		tmp7[3] = (uint32_t(tmp6) >> 0) & 0xFF;
		in.append(tmp7, 4);
		in.append(in0);
	}
	char *out = NULL;
	int outLen = 0;
	Go2cppFn_QrcodePngToText((char *)in.data(), in.length(), &out, &outLen);
	QrcodePngToText_Resp retValue;
	int outIdx = 0;
	{
		{
			uint32_t tmp8 = 0;
			uint32_t tmp9 = uint32_t(uint8_t(out[outIdx+0]) << 24);
			uint32_t tmp10 = uint32_t(uint8_t(out[outIdx+1]) << 16);
			uint32_t tmp11 = uint32_t(uint8_t(out[outIdx+2]) << 8);
			uint32_t tmp12 = uint32_t(uint8_t(out[outIdx+3]) << 0);
			tmp8 = tmp9 | tmp10 | tmp11 | tmp12;
			outIdx+=4;
			retValue.ErrMsg = std::string(out+outIdx, out+outIdx+tmp8);
			outIdx+=tmp8;
		}
		{
			uint32_t tmp13 = 0;
			uint32_t tmp14 = uint32_t(uint8_t(out[outIdx+0]) << 24);
			uint32_t tmp15 = uint32_t(uint8_t(out[outIdx+1]) << 16);
			uint32_t tmp16 = uint32_t(uint8_t(out[outIdx+2]) << 8);
			uint32_t tmp17 = uint32_t(uint8_t(out[outIdx+3]) << 0);
			tmp13 = tmp14 | tmp15 | tmp16 | tmp17;
			outIdx+=4;
			retValue.Text = std::string(out+outIdx, out+outIdx+tmp13);
			outIdx+=tmp13;
		}
	}
	if (out != NULL) {
		free(out);
	}
	return retValue;
}

TextToQrcodePng_Resp TextToQrcodePng(std::string in0, int32_t in1){
	std::string in;
	{
		uint32_t tmp7 = in0.length();
		char tmp8[4];
		tmp8[0] = (uint32_t(tmp7) >> 24) & 0xFF;
		tmp8[1] = (uint32_t(tmp7) >> 16) & 0xFF;
		tmp8[2] = (uint32_t(tmp7) >> 8) & 0xFF;
		tmp8[3] = (uint32_t(tmp7) >> 0) & 0xFF;
		in.append(tmp8, 4);
		in.append(in0);
	}
	{
		char tmp9[4];
		tmp9[0] = (uint32_t(in1) >> 24) & 0xFF;
		tmp9[1] = (uint32_t(in1) >> 16) & 0xFF;
		tmp9[2] = (uint32_t(in1) >> 8) & 0xFF;
		tmp9[3] = (uint32_t(in1) >> 0) & 0xFF;
		in.append(tmp9, 4);
	}
	char *out = NULL;
	int outLen = 0;
	Go2cppFn_TextToQrcodePng((char *)in.data(), in.length(), &out, &outLen);
	TextToQrcodePng_Resp retValue;
	int outIdx = 0;
	{
		{
			uint32_t tmp10 = 0;
			uint32_t tmp11 = uint32_t(uint8_t(out[outIdx+0]) << 24);
			uint32_t tmp12 = uint32_t(uint8_t(out[outIdx+1]) << 16);
			uint32_t tmp13 = uint32_t(uint8_t(out[outIdx+2]) << 8);
			uint32_t tmp14 = uint32_t(uint8_t(out[outIdx+3]) << 0);
			tmp10 = tmp11 | tmp12 | tmp13 | tmp14;
			outIdx+=4;
			retValue.ErrMsg = std::string(out+outIdx, out+outIdx+tmp10);
			outIdx+=tmp10;
		}
		{
			uint32_t tmp15 = 0;
			uint32_t tmp16 = uint32_t(uint8_t(out[outIdx+0]) << 24);
			uint32_t tmp17 = uint32_t(uint8_t(out[outIdx+1]) << 16);
			uint32_t tmp18 = uint32_t(uint8_t(out[outIdx+2]) << 8);
			uint32_t tmp19 = uint32_t(uint8_t(out[outIdx+3]) << 0);
			tmp15 = tmp16 | tmp17 | tmp18 | tmp19;
			outIdx+=4;
			retValue.PngBytes = std::string(out+outIdx, out+outIdx+tmp15);
			outIdx+=tmp15;
		}
	}
	if (out != NULL) {
		free(out);
	}
	return retValue;
}

